# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3-8B
torch_dtype: bfloat16
attn_implementation: flash_attention_2
trust_remote_code: false

# Data training arguments
dataset_mixer:
  Anthropic/hh-rlhf: 1.0
dataset_dir: harmless-base
dataset_splits:
  - train
  - test
preprocessing_num_workers: 8

# SFT trainer arguments
bf16: true
fp16: false
do_eval: true
eval_strategy: steps
eval_steps: 500
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-05
lr_scheduler_type: cosine
warmup_ratio: 0.1
num_train_epochs: 1
max_seq_length: 500
max_steps: -1
optim: adamw_torch
logging_steps: 10
log_level: info
output_dir: outputs/llama-3-8b-base-hh-harmless-base-sft
run_name: llama-3-8b-base-hh-harmless-base-sft
save_strategy: steps
save_steps: 500
save_total_limit: 3
report_to:
  - wandb
seed: 42
push_to_hub: false
overwrite_output_dir: true
